# Generated by Django 3.2.16 on 2022-11-19 13:37

from django.db import migrations, models
import django.db.models.deletion
import django_spanner


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteHub',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('disposal_service_company_ID', models.IntegerField()),
                ('location_longitude', models.FloatField()),
                ('location_latitude', models.FloatField()),
                ('address_string_1', models.CharField(max_length=100)),
                ('address_string_2', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('max_wait_time_days', models.IntegerField()),
                ('average_weight_per_liter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteTypeReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=django_spanner.gen_rand_int64, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_to_be_thrown', models.BooleanField(default=False)),
                ('remote_hub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_hub_id_wtr', to='app.remotehub')),
                ('waste_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_type_id_wtr', to='app.wastetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='container',
            name='remote_hub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_hub_id_c', to='app.wastetype'),
        ),
        migrations.AddField(
            model_name='container',
            name='waste_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_type_id_c', to='app.wastetype'),
        ),
    ]
