# Generated by Django 3.2.16 on 2022-11-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221119_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalServiceCompanies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=225)),
                ('contact', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=False)),
                ('registration_number', models.CharField(max_length=10)),
                ('disposal_service_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disposalservicecompanies')),
            ],
        ),
    ]
